version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - v1-pkg-cache
      - run:
          name: Provide an .env file as test config
          command: base64 -d <<< "$PLAYGROUND_ENV" > .env
      - run: go get -u golang.org/x/lint/golint
      - run: go get github.com/jstemmer/go-junit-report
      - run:
          name: Run unit tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            DEBUG=1 make test | tee ${TEST_RESULTS}/go-test.out
      - save_cache: # Store cache in the /go/pkg directory
          key: pkg-cache
          paths:
            - "/go/pkg"
      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
